name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Specify Node Version
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Compile Typescript
      - name: Build Project
        run: npm run build

      # Run Test Cases
      - name: Run Tests
        run: npm run test
